version: "3.9"

services:
  app:
    container_name: bun_app_container
    build:
      context: ./.docker/app
    ports:
      - 8000:8000
    volumes:
      - .:/workspace
      - bun_cache:/bun_dir
    environment:
      - NODE_ENV=developmentstall --frozen-lockfile
    stdin_open: true
    tty: true

  db:
    container_name: bun_db_container
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - bun_db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_ALLOW_EMPTY_PASSWORD: "yes"
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DEV_DATABASE: ${POSTGRES_DEV_DATABASE}

  redis:
    container_name: bun_redis_container
    image: redis
    ports:
      - 6379:6379
    volumes:
      - bun_cache:/data

volumes:
  bun_cache:
  bun_db_volume:

