/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */







declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
  Role: "ADMIN" | "USER"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  AuthPayload: { // root type
    token: string; // String!
  }
  Board: { // root type
    content: string; // String!
    id: number; // Int!
    user_id: number; // Int!
  }
  Mutation: {};
  PersonalBankAccount: { // root type
    account_number: string; // String!
    balance: number; // Int!
    id: number; // Int!
    is_active: boolean; // Boolean!
    user_id: number; // Int!
  }
  Query: {};
  User: { // root type
    boards?: Array<NexusGenRootTypes['Board'] | null> | null; // [Board]
    email: string; // String!
    id: number; // Int!
    name: string; // String!
    password: string; // String!
    role: NexusGenEnums['Role']; // Role!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  AuthPayload: { // field return type
    token: string; // String!
  }
  Board: { // field return type
    content: string; // String!
    id: number; // Int!
    user_id: number; // Int!
  }
  Mutation: { // field return type
    addPayrollToUser: NexusGenRootTypes['PersonalBankAccount']; // PersonalBankAccount!
    createBoard: NexusGenRootTypes['Board']; // Board!
    createPersonalBankAccount: NexusGenRootTypes['PersonalBankAccount']; // PersonalBankAccount!
    signin: NexusGenRootTypes['AuthPayload']; // AuthPayload!
    signup: NexusGenRootTypes['User']; // User!
    updateBoard: NexusGenRootTypes['Board']; // Board!
  }
  PersonalBankAccount: { // field return type
    account_number: string; // String!
    balance: number; // Int!
    id: number; // Int!
    is_active: boolean; // Boolean!
    user_id: number; // Int!
  }
  Query: { // field return type
    board: NexusGenRootTypes['Board']; // Board!
    boards: Array<NexusGenRootTypes['Board'] | null>; // [Board]!
    hello: string; // String!
    personalBankAccount: NexusGenRootTypes['PersonalBankAccount']; // PersonalBankAccount!
    user: NexusGenRootTypes['User']; // User!
    users: Array<NexusGenRootTypes['User'] | null>; // [User]!
  }
  User: { // field return type
    boards: Array<NexusGenRootTypes['Board'] | null> | null; // [Board]
    email: string; // String!
    id: number; // Int!
    name: string; // String!
    password: string; // String!
    role: NexusGenEnums['Role']; // Role!
  }
}

export interface NexusGenFieldTypeNames {
  AuthPayload: { // field return type name
    token: 'String'
  }
  Board: { // field return type name
    content: 'String'
    id: 'Int'
    user_id: 'Int'
  }
  Mutation: { // field return type name
    addPayrollToUser: 'PersonalBankAccount'
    createBoard: 'Board'
    createPersonalBankAccount: 'PersonalBankAccount'
    signin: 'AuthPayload'
    signup: 'User'
    updateBoard: 'Board'
  }
  PersonalBankAccount: { // field return type name
    account_number: 'String'
    balance: 'Int'
    id: 'Int'
    is_active: 'Boolean'
    user_id: 'Int'
  }
  Query: { // field return type name
    board: 'Board'
    boards: 'Board'
    hello: 'String'
    personalBankAccount: 'PersonalBankAccount'
    user: 'User'
    users: 'User'
  }
  User: { // field return type name
    boards: 'Board'
    email: 'String'
    id: 'Int'
    name: 'String'
    password: 'String'
    role: 'Role'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    addPayrollToUser: { // args
      amount: number; // Int!
      user_id: number; // Int!
    }
    createBoard: { // args
      content: string; // String!
      user_id: number; // Int!
    }
    createPersonalBankAccount: { // args
      account_number: string; // String!
      balance?: number | null; // Int
      is_active?: boolean | null; // Boolean
      user_id: number; // Int!
    }
    signin: { // args
      email: string; // String!
      password: string; // String!
    }
    signup: { // args
      email: string; // String!
      name: string; // String!
      password: string; // String!
      role: NexusGenEnums['Role']; // Role!
    }
    updateBoard: { // args
      content: string; // String!
      id: number; // Int!
    }
  }
  Query: {
    board: { // args
      id: number; // Int!
    }
    personalBankAccount: { // args
      id: number; // Int!
      user_id: number; // Int!
    }
    user: { // args
      id: number; // Int!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: any;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}